src/Pgpg.Web/Areas/Admin/Models/Layout/HeaderViewModel.cs
using System.Collections.Generic;
using Abp.Localization;
using Pgpg.Application.Sessions.Dto;

namespace Pgpg.Web.Areas.Admin.Models.Layout
{
    public class HeaderViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }

        public LanguageInfo CurrentLanguage { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public bool IsImpersonatedLogin { get; set; }

        public string GetShownLoginName()
        {
            var userName = "<span id=\"HeaderCurrentUserName\">" + LoginInformations.User.UserName + "</span>";

            if (!IsMultiTenancyEnabled)
            {
                return userName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + userName
                : LoginInformations.Tenant.TenancyName + "\\" + userName;
        }
    }
}

src/Pgpg.Web/Models/Layout/HeaderViewModel.cs
using System.Collections.Generic;
using Abp.Application.Navigation;
using Abp.Localization;
using Pgpg.Application.Sessions.Dto;

namespace Pgpg.Web.Models.Layout
{
    public class HeaderViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }
        
        public IReadOnlyList<LanguageInfo> Languages { get; set; }

        public LanguageInfo CurrentLanguage { get; set; }
        
        public UserMenu Menu { get; set; }
        
        public string CurrentPageName { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public bool TenantRegistrationEnabled { get; set; }

        public string GetShownLoginName()
        {
            if (!IsMultiTenancyEnabled)
            {
                return LoginInformations.User.UserName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + LoginInformations.User.UserName
                : LoginInformations.Tenant.TenancyName + "\\" + LoginInformations.User.UserName;
        }
    }
}

src/Pgpg.Web/Areas/Admin/Views/Shared/Components/AdminFooter/AdminFooterViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Pgpg.Application.Sessions;
using Pgpg.Web.Areas.Admin.Models.Layout;

namespace Pgpg.Web.Areas.Admin.Views.Shared.Components.AdminFooter
{
    public class AdminFooterViewComponent : ViewComponent
    {
        private readonly ISessionAppService _sessionAppService;

        public AdminFooterViewComponent(
            ISessionAppService sessionAppService)
        {
            _sessionAppService = sessionAppService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var footerModel = new FooterViewModel
            {
                LoginInformations = await _sessionAppService.GetCurrentLoginInformations()
            };

            return View(footerModel);
        }
    }
}

src/Pgpg.Web/Areas/Admin/Views/Shared/Components/AdminHeader/AccountLanguagesViewComponent.cs
using System.Threading.Tasks;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Microsoft.AspNetCore.Mvc;
using Pgpg.Application.Sessions;
using Pgpg.Web.Areas.Admin.Models.Layout;

namespace Pgpg.Web.Areas.Admin.Views.Shared.Components.AdminHeader
{
    public class AdminHeaderViewComponent : ViewComponent
    {
        private readonly ILanguageManager _languageManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ISessionAppService _sessionAppService;
        private readonly IAbpSession _abpSession;

        public AdminHeaderViewComponent(
            IMultiTenancyConfig multiTenancyConfig, 
            ISessionAppService sessionAppService,
            IAbpSession abpSession, ILanguageManager languageManager)
        {
            _multiTenancyConfig = multiTenancyConfig;
            _sessionAppService = sessionAppService;
            _abpSession = abpSession;
            _languageManager = languageManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var headerModel = new HeaderViewModel
            {
                LoginInformations = await _sessionAppService.GetCurrentLoginInformations(),
                Languages = _languageManager.GetLanguages(),
                CurrentLanguage = _languageManager.CurrentLanguage,
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
                IsImpersonatedLogin = _abpSession.ImpersonatorUserId.HasValue
            };

            return View(headerModel);
        }
    }
}

src/Pgpg.Web/Areas/Admin/Views/Shared/Components/AdminSideBar/AdminSideBarViewComponent.cs
using System.Threading.Tasks;
using Abp.Application.Navigation;
using Abp.Runtime.Session;
using Microsoft.AspNetCore.Mvc;
using Pgpg.Web.Areas.Admin.Models.Layout;
using Pgpg.Web.Areas.Admin.Startup;

namespace Pgpg.Web.Areas.Admin.Views.Shared.Components.AdminSideBar
{
    public class AdminSideBarViewComponent : ViewComponent
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IAbpSession _abpSession;

        public AdminSideBarViewComponent(
            IUserNavigationManager userNavigationManager, IAbpSession abpSession)
        {
            _userNavigationManager = userNavigationManager;
            _abpSession = abpSession;
        }

        public async Task<IViewComponentResult> InvokeAsync(string currentPageName = null)
        {
            var sidebarModel = new SidebarViewModel
            {
                Menu = await _userNavigationManager.GetMenuAsync(AdminNavigationProvider.MenuName, _abpSession.ToUserIdentifier()),
                CurrentPageName = currentPageName
            };

            return View(sidebarModel);
        }
    }
}

src/Pgpg.Web/Controllers/TenantRegistrationController.cs
using System;
using System.Threading.Tasks;
using Abp.Authorization.Users;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Domain.Uow;
using Abp.UI;
using Abp.Zero.Configuration;
using Pgpg.Web.Models.TenantRegistration;
using Microsoft.AspNetCore.Mvc;
using Pgpg.Web.Identity;
using PaulMiami.AspNetCore.Mvc.Recaptcha;
using Pgpg.Application.Authorization;
using Pgpg.Core.Authorization.Users;
using Pgpg.Core.Configuration;
using Pgpg.Core.Debugging;
using Pgpg.Core.Editions;
using Pgpg.Core.MultiTenancy;
using Pgpg.Core.Notifications;

namespace Pgpg.Web.Controllers
{
    public class TenantRegistrationController : PgpgControllerBase
    {
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly TenantManager _tenantManager;
        private readonly UserManager _userManager;
        private readonly EditionManager _editionManager;
        private readonly IAppNotifier _appNotifier;
        private readonly AbpLoginResultTypeHelper _abpLoginResultTypeHelper;
        private readonly IRecaptchaValidationService _recaptchaValidationService;
        private readonly LogInManager _logInManager;
        private readonly SignInManager _signInManager;

        public TenantRegistrationController(
            IMultiTenancyConfig multiTenancyConfig,
            TenantManager tenantManager,
            EditionManager editionManager,
            IAppNotifier appNotifier,
            UserManager userManager,
            AbpLoginResultTypeHelper abpLoginResultTypeHelper, 
            IRecaptchaValidationService recaptchaValidationService, 
            LogInManager logInManager,
            SignInManager signInManager)
        {
            _multiTenancyConfig = multiTenancyConfig;
            _tenantManager = tenantManager;
            _editionManager = editionManager;
            _appNotifier = appNotifier;
            _userManager = userManager;
            _abpLoginResultTypeHelper = abpLoginResultTypeHelper;
            _recaptchaValidationService = recaptchaValidationService;
            _logInManager = logInManager;
            _signInManager = signInManager;
        }

        public ActionResult Index()
        {
            CheckTenantRegistrationIsEnabled();

            ViewBag.UseCaptcha = UseCaptchaOnRegistration();
            ViewBag.PasswordComplexitySetting = SettingManager.GetSettingValue(AppSettings.Security.PasswordComplexity).Replace("\"","");

            return View();
        }

        [HttpPost]
        [UnitOfWork]
        public virtual async Task<ActionResult> Register(TenantRegistrationViewModel model)
        {
            try
            {
                CheckTenantRegistrationIsEnabled();

                if (UseCaptchaOnRegistration())
                {
                    await CheckCaptchaResponseAsync(_recaptchaValidationService);
                }

                //Getting host-specific settings
                var isNewRegisteredTenantActiveByDefault = await SettingManager.GetSettingValueForApplicationAsync<bool>(AppSettings.TenantManagement.IsNewRegisteredTenantActiveByDefault);
                var isEmailConfirmationRequiredForLogin = await SettingManager.GetSettingValueForApplicationAsync<bool>(AbpZeroSettingNames.UserManagement.IsEmailConfirmationRequiredForLogin);
                var defaultEditionIdValue = await SettingManager.GetSettingValueForApplicationAsync(AppSettings.TenantManagement.DefaultEdition);
                int? defaultEditionId = null;

                if (!string.IsNullOrEmpty(defaultEditionIdValue) && (await _editionManager.FindByIdAsync(Convert.ToInt32(defaultEditionIdValue)) != null))
                {
                    defaultEditionId = Convert.ToInt32(defaultEditionIdValue);
                }

                CurrentUnitOfWork.SetTenantId(null);

                var tenantId = await _tenantManager.CreateWithAdminUserAsync(
                  model.TenancyName,
                  model.Name,
                  model.AdminPassword,
                  model.AdminEmailAddress,
                  null,
                  isNewRegisteredTenantActiveByDefault,
                  defaultEditionId,
                  false,
                  isEmailConfirmationRequiredForLogin);

                ViewBag.UseCaptcha = UseCaptchaOnRegistration();

                var tenant = await _tenantManager.GetByIdAsync(tenantId);
                await _appNotifier.NewTenantRegisteredAsync(tenant);

                CurrentUnitOfWork.SetTenantId(tenant.Id);

                var user = await _userManager.FindByNameAsync(Core.Authorization.Users.User.AdminUserName);

                //Directly login if possible
                if (user.IsActive && (user.IsEmailConfirmed || !isEmailConfirmationRequiredForLogin))
                {
                    var loginResult = await GetLoginResultAsync(user.UserName, model.AdminPassword, tenant.TenancyName);

                    if (loginResult.Result == AbpLoginResultType.Success)
                    {
                        await _signInManager.SignOutAllAndSignInAsync(loginResult.Identity);

                        return Redirect(Url.Action("Index", "Home", new {area = "Admin"}));
                    }

                    Logger.Warn("New registered user could not be login. This should not be normally. login result: " + loginResult.Result);
                }

                return View("RegisterResult", new TenantRegisterResultViewModel
                {
                    TenancyName = model.TenancyName,
                    Name = model.Name,
                    UserName = Core.Authorization.Users.User.AdminUserName,
                    EmailAddress = model.AdminEmailAddress,
                    IsActive = isNewRegisteredTenantActiveByDefault,
                    IsEmailConfirmationRequired = isEmailConfirmationRequiredForLogin
                });
            }
            catch (UserFriendlyException ex)
            {
                ViewBag.UseCaptcha = UseCaptchaOnRegistration();
                ViewBag.ErrorMessage = ex.Message;

                return View("Index", model);
            }
        }

        private bool IsSelfRegistrationEnabled()
        {
            return SettingManager.GetSettingValueForApplication<bool>(AppSettings.TenantManagement.AllowSelfRegistration);
        }

        private void CheckTenantRegistrationIsEnabled()
        {
            if (!IsSelfRegistrationEnabled())
            {
                throw new UserFriendlyException(L("SelfTenantRegistrationIsDisabledMessage_Detail"));
            }

            if (!_multiTenancyConfig.IsEnabled)
            {
                throw new UserFriendlyException(L("MultiTenancyIsNotEnabled"));
            }
        }

        private bool UseCaptchaOnRegistration()
        {
            if (DebugHelper.IsDebug)
            {
                return false;
            }

            return SettingManager.GetSettingValueForApplication<bool>(AppSettings.TenantManagement.UseCaptchaOnRegistration);
        }

        private async Task<AbpLoginResult<Tenant, User>> GetLoginResultAsync(string usernameOrEmailAddress, string password, string tenancyName)
        {
            var loginResult = await _logInManager.LoginAsync(usernameOrEmailAddress, password, tenancyName);

            switch (loginResult.Result)
            {
                case AbpLoginResultType.Success:
                    return loginResult;
                default:
                    throw _abpLoginResultTypeHelper.CreateExceptionForFailedLoginAttempt(loginResult.Result, usernameOrEmailAddress, tenancyName);
            }
        }
    }
}

src/Pgpg.Web/Views/Shared/Components/AccountLanguages/AccountLanguagesViewComponent.cs
using System.Threading.Tasks;
using Abp.Localization;
using Microsoft.AspNetCore.Mvc;

namespace Pgpg.Web.Views.Shared.Components.AccountLanguages
{
    public class AccountLanguagesViewComponent : ViewComponent
    {
        private readonly ILanguageManager _languageManager;

        public AccountLanguagesViewComponent(ILanguageManager languageManager)
        {
            _languageManager = languageManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new LanguageSelectionViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages(),
                CurrentUrl = Request.Path
            };

            return View(model);
        }
    }
}

src/Pgpg.Web/Views/Shared/Components/Header/HeaderViewComponent.cs
using System.Threading.Tasks;
using Abp.Application.Navigation;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Microsoft.AspNetCore.Mvc;
using Pgpg.Application.Sessions;
using Pgpg.Core.Configuration;
using Pgpg.Web.Models.Layout;
using Pgpg.Web.Startup;

namespace Pgpg.Web.Views.Shared.Components.Header
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly IAbpSession _abpSession;
        private readonly ILanguageManager _languageManager;
        private readonly ISettingManager _settingManager;

        public HeaderViewComponent(
            ISessionAppService sessionAppService, 
            IUserNavigationManager userNavigationManager, 
            IMultiTenancyConfig multiTenancyConfig,
            IAbpSession abpSession,
            ILanguageManager languageManager, 
            ISettingManager settingManager)
        {
            _sessionAppService = sessionAppService;
            _userNavigationManager = userNavigationManager;
            _multiTenancyConfig = multiTenancyConfig;
            _abpSession = abpSession;
            _languageManager = languageManager;
            _settingManager = settingManager;
        }

        public async Task<IViewComponentResult> InvokeAsync(string currentPageName = "")
        {
            var headerModel = new HeaderViewModel();

            if (_abpSession.UserId.HasValue)
            {
                headerModel.LoginInformations = await _sessionAppService.GetCurrentLoginInformations();
            }

            headerModel.Languages = _languageManager.GetLanguages();
            headerModel.CurrentLanguage = _languageManager.CurrentLanguage;

            headerModel.Menu = await _userNavigationManager.GetMenuAsync(
                FrontEndNavigationProvider.MenuName,
                _abpSession.ToUserIdentifier()
            );

            headerModel.CurrentPageName = currentPageName;

            headerModel.IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled;
            headerModel.TenantRegistrationEnabled = await _settingManager.GetSettingValueAsync<bool>(AppSettings.TenantManagement.AllowSelfRegistration);

            return View(headerModel);
        }
    }
}

src/Pgpg.Web/Views/Shared/Components/Header/Default.cshtml
@using System.Threading.Tasks
@using Pgpg.Web.Views.Shared.Components.Header
@model Pgpg.Web.Models.Layout.HeaderViewModel
<div class="pre-header">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 additional-shop-info">
                <ul class="list-unstyled list-inline">
                    <li><i class="fa fa-phone"></i><span>QQ:95572457</span></li>
                    <li><i class="fa fa-envelope-o"></i><span>95572457@qq.com</span></li>
                </ul>
            </div>
            <div class="col-md-6 col-sm-6 additional-nav">
                <ul class="list-unstyled list-inline pull-right">
                    @if (Model.Languages.Count > 1)
                    {
                        <li>
                            <div id="LanguageDropDown" class="btn-group dropdown">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-delay="1000" data-close-others="true"><i class="@Model.CurrentLanguage.Icon"></i> @Model.CurrentLanguage.DisplayName <i class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    @foreach (var language in Model.Languages)
                                    {
                                        if (Model.CurrentLanguage.Name == language.Name)
                                        {
                                            continue;
                                        }

                                        <li class="language-menu-item">
                                            <a href="@Url.Action("ChangeCulture", "AbpLocalization")?cultureName=@(language.Name)&returnUrl=@Context.Request.Path"><i class="@language.Icon"></i> <span>@language.DisplayName</span></a>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </li>
                    }
                    @if (Model.LoginInformations == null && Model.IsMultiTenancyEnabled && Model.TenantRegistrationEnabled)
                    {
                        <li>
                            <a href="@Url.Action("Index", "TenantRegistration")">@L("NewTenant")</a>
                        </li>
                    }
                    <li>
                        @if (Model.LoginInformations != null)
                        {
                            <a href="@Url.Action("Index", "Home", new { area = "Admin" })">@Model.GetShownLoginName() (进入后台)</a>
                            <a href="@Url.Action("Logout", "Account")">@L("Logout")</a>
                        }
                        else
                        {
                            <a href="@Url.Action("Login", "Account")">@L("LogIn")</a>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="header">
    <div class="container">
        <a class="site-logo" href="@Url.Action("Index", "Home")">
            <img src="~/Common/Images/app-logo-on-light.png" alt="" width="168" height="33" />
        </a>
        <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>
        <div class="header-navigation pull-right font-transform-inherit">
            <ul>
                @foreach (var menuItem in @Model.Menu.Items)
                {
                    @Html.Partial("Components/Header/_HeaderMenuItem", new HeaderMenuItemViewModel(menuItem, 0, Model.CurrentPageName))
                }
            </ul>
        </div>
    </div>
</div>

src/Pgpg.Web/Views/Shared/Components/Header/_HeaderMenuItem.cshtml
@using Abp.Collections.Extensions
@using Abp.Extensions
@using System.Threading.Tasks
@using Pgpg.Web.Views
@using Pgpg.Web.Views.Shared.Components.Header
@model HeaderMenuItemViewModel
<li class="@(Model.MenuItem.Name == Model.CurrentPageName ? "active" : "") @(Model.MenuItem.Items.IsNullOrEmpty() ? "" : (Model.CurrentLevel == 0 ? "dropdown" : "dropdown-submenu"))">
    @if (Model.MenuItem.Items.IsNullOrEmpty())
    {
        if (!Model.MenuItem.Url.IsNullOrEmpty())
        {
            <a href="@(UrlChecker.IsRooted(Model.MenuItem.Url) ? Model.MenuItem.Url : (ApplicationPath + Model.MenuItem.Url))">@Model.MenuItem.DisplayName</a>
        }
        else
        {
            <a href="@ApplicationPath">@Model.MenuItem.DisplayName</a>
        }
    }
    else
    {
        <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">
            @Model.MenuItem.DisplayName
        </a>
            <ul class="dropdown-menu">
                @foreach (var childMenuItem in Model.MenuItem.Items)
                {
                    @Html.Partial("Components/Header/_HeaderMenuItem", new HeaderMenuItemViewModel(childMenuItem, Model.CurrentLevel + 1, Model.CurrentPageName))
                }
            </ul>
    }
</li>